version: "3"
volumes:
  dados:
networks:
  banco:
  web:
services:
  db:
    image: postgres:9.6
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      # Volume dos dados
      - ./db:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    container_name: frontend
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    container_name: app
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    depends_on:
      - db
    networks:
      - banco
      - web
