version: "3"
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:9.6
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      # Volume dos dados
      - ./db:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    container_name: frontend
    volumes:
      - ./web:/usr/share/nginx/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    container_name: app
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    environment:
      - DB_HOST
      - DB_USER
      - DB_NAME
      - DB_PASSWORD
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
    depends_on:
      - db
      - queue
    networks:
      - banco
      - web
      - fila
  queue:
    image: redis:3.2
    container_name: queue
    networks:
      - fila
  worker:
    build: worker
    working_dir: /worker
    volumes:
      - ./worker:/worker
    command: worker.py
    environment:
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
    networks:
      - fila
    depends_on:
      - queue
